/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Extract project ID from Supabase URL
const getProjectId = () => {
  const url = import.meta.env.VITE_SUPABASE_URL || 'http://127.0.0.1:54321'
  if (url.includes('localhost') || url.includes('127.0.0.1')) {
    return 'local'
  }
  // Extract project ID from production URL like https://rjppzjhkarsgzvemdkqf.supabase.co
  const match = url.match(/https:\/\/([^.]+)\.supabase\.co/)
  return match ? match[1] : 'local'
}

export const projectId = getProjectId()
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"